// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD3QiceMDBPtySWBdHa3vDFGY7HxPtUTQ',
    appId: '1:1067241701328:web:40679eec525a92d9f403d5',
    messagingSenderId: '1067241701328',
    projectId: 'lalamon-30884',
    authDomain: 'lalamon-30884.firebaseapp.com',
    storageBucket: 'lalamon-30884.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfBgUImSoQ6HtkIYMf3oWTTqj0s073s4s',
    appId: '1:1067241701328:android:8a2bb868a8030c6cf403d5',
    messagingSenderId: '1067241701328',
    projectId: 'lalamon-30884',
    storageBucket: 'lalamon-30884.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAfafpGH0BKgqIfkMkT4M2OXB6KT-0Ha4',
    appId: '1:1067241701328:ios:f1bfd7660a57b401f403d5',
    messagingSenderId: '1067241701328',
    projectId: 'lalamon-30884',
    storageBucket: 'lalamon-30884.firebasestorage.app',
    iosBundleId: 'com.example.lalamon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAfafpGH0BKgqIfkMkT4M2OXB6KT-0Ha4',
    appId: '1:1067241701328:ios:f1bfd7660a57b401f403d5',
    messagingSenderId: '1067241701328',
    projectId: 'lalamon-30884',
    storageBucket: 'lalamon-30884.firebasestorage.app',
    iosBundleId: 'com.example.lalamon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD3QiceMDBPtySWBdHa3vDFGY7HxPtUTQ',
    appId: '1:1067241701328:web:4e9099c58b1c7e77f403d5',
    messagingSenderId: '1067241701328',
    projectId: 'lalamon-30884',
    authDomain: 'lalamon-30884.firebaseapp.com',
    storageBucket: 'lalamon-30884.firebasestorage.app',
  );
}
